version: '3.1'

services:
  app: 
    build: 
      context: .
      dockerfile: DockerFile
    container_name: quick-auth-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECREY_KEY: ${JWT_SECREY_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SENDER_EMAIL: ${SENDER_EMAIL}
      SENDER_NAME: ${SENDER_NAME}
      ETHEREAL_EMAIL: ${ETHEREAL_EMAIL}
      ETHEREAL_PASSWORD: ${ETHEREAL_PASSWORD}
    networks:
      - app-network
  postgres:
    image: postgres
    container_name: quick-auth-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: quick_auth_db
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
